import React from 'react';
import { FileText, AlertTriangle } from 'lucide-react';

const TermsPage = () => {
  const sections = [
    {
      title: '1. Acceptance of Terms',
      content: `By accessing, registering on, or using the NourishLink Smart Food Donation Platform ("Platform"), you agree to be bound by these Terms and Conditions ("Terms"). If you do not agree to all of these Terms, you must not use the Platform.
These Terms constitute a legally binding agreement between you ("User") and NourishLink ("we", "us", "our").`,
    },
    {
      title: '2. Eligibility',
      content: `• You must be at least 18 years of age to register and use this Platform.
• You must provide accurate, current, and complete information during registration and keep it updated.
• Organizations (NGOs, food banks, restaurants) must provide valid registration or identification details.
• We reserve the right to verify user identities and organization credentials at any time.`,
    },
    {
      title: '3. User Accounts & Roles',
      content: `The Platform supports the following roles:
• **Donor**: Individuals or organizations that list surplus food for donation.
• **NGO / Receiver**: Registered organizations that request and collect food donations.
• **Volunteer / Pickup Partner**: Individuals who assist with food pickup and delivery.
• **Admin**: Platform administrators with elevated privileges (created through system provisioning only).

You are responsible for maintaining the confidentiality of your account credentials. You agree to notify us immediately of any unauthorized access to your account. We are not liable for any loss arising from unauthorized use of your account.`,
    },
    {
      title: '4. Food Donations',
      content: `**Donors agree to:**
• List only food that is safe for consumption, not expired, and properly stored.
• Provide accurate descriptions of food items, quantities, preparation dates, and expiry dates.
• Provide accurate food safety details including storage type, allergens, and handling instructions.
• Make food available for pickup at the specified date, time, and location.
• Not list prohibited items including alcohol, tobacco, controlled substances, or any non-food items.

**Receivers/NGOs agree to:**
• Verify food quality and safety upon collection.
• Use collected food only for charitable distribution to individuals in need.
• Not resell or commercially exploit donated food.
• Handle food safely during transport and distribution.`,
    },
    {
      title: '5. Pickup & Delivery',
      content: `• The Platform facilitates matching between donors and receivers but does not directly handle food pickup or delivery unless through registered volunteer partners.
• Both donors and receivers are responsible for coordinating pickup logistics.
• Volunteers act as independent participants; the Platform does not employ them.
• The Platform is not responsible for food quality after it leaves the donor's custody.
• Estimated pickup/delivery times are approximate and not guaranteed.`,
    },
    {
      title: '6. Limitation of Liability',
      content: `• The Platform serves as a technology facilitator connecting donors, receivers, and volunteers. We do not inspect, verify, or guarantee the quality, safety, or fitness of any food listed.
• NourishLink is not responsible for any illness, injury, loss, or damage arising from the consumption, handling, or distribution of donated food.
• We are not liable for indirect, incidental, special, consequential, or punitive damages arising from your use of the Platform.
• Our total liability is limited to the amount you have paid to use the Platform (if any).
• We do not guarantee uninterrupted, error-free, or secure access to the Platform.`,
    },
    {
      title: '7. Intellectual Property',
      content: `• All content, design, logos, trademarks, and software on the Platform are owned by NourishLink or its licensors.
• You may not copy, modify, distribute, or create derivative works from any Platform content without prior written permission.
• User-generated content (listings, messages, reviews) remains your property, but you grant us a non-exclusive, worldwide, royalty-free license to use, display, and distribute it on the Platform.
• Donation certificates generated by the Platform are for personal use and record-keeping only.`,
    },
    {
      title: '8. Prohibited Conduct',
      content: `You agree not to:
• Provide false or misleading information about food items, quantities, or safety details.
• Use the Platform for commercial gain, resale, or any non-charitable purpose.
• Harass, threaten, or abuse other users.
• Attempt to gain unauthorized access to Platform systems, accounts, or data.
• Upload malicious code, viruses, or any harmful content.
• Circumvent or manipulate the Platform's matching or notification systems.
• Create multiple accounts for the same individual or organization.
Violations may result in immediate account suspension or termination.`,
    },
    {
      title: '9. Dispute Resolution',
      content: `• Any disputes between users (e.g., donor and receiver) should first be attempted to resolve through direct communication.
• If unresolved, disputes may be reported to Platform administrators through the contact or support channels.
• We may mediate disputes at our discretion but are not obligated to do so.
• These Terms are governed by and construed in accordance with the laws of India.
• Any legal proceedings shall be subject to the exclusive jurisdiction of the courts in New Delhi, India.`,
    },
    {
      title: '10. Account Termination',
      content: `• You may deactivate your account at any time by contacting support.
• We reserve the right to suspend, restrict, or terminate accounts that violate these Terms, engage in fraudulent activity, or remain inactive for extended periods.
• Upon termination, your right to use the Platform ceases immediately.
• Data retention after account termination is governed by our Privacy Policy.`,
    },
    {
      title: '11. Amendments',
      content: `• We may modify these Terms at any time. Significant changes will be communicated through in-platform notifications and/or email.
• Your continued use of the Platform after changes constitutes acceptance of the updated Terms.
• The "last updated" date at the top of this page reflects the most recent revision.`,
    },
    {
      title: '12. Contact Information',
      content: `For questions about these Terms and Conditions:
• **Email**: support@nourishlink.org
• **Phone**: +91 98765 43210
• **Address**: Green Park Avenue, New Delhi — 110016, India`,
    },
  ];

  return (
    <div>
      <section style={{
        background: 'linear-gradient(135deg, #0f172a, #1e293b)',
        color: '#ffffff', padding: '4rem 1.5rem', textAlign: 'center',
      }}>
        <FileText size={36} style={{ color: 'var(--primary-400)', marginBottom: '1rem' }} />
        <h1 style={{ fontSize: '2.25rem', fontWeight: 800, marginBottom: '0.75rem' }}>Terms & Conditions</h1>
        <p style={{ color: '#94a3b8', fontSize: '0.95rem' }}>Last updated: August 2026</p>
      </section>

      <section style={{ padding: '3rem 1.5rem', background: 'var(--bg-main)' }}>
        <div className="container" style={{ maxWidth: '820px' }}>
          {/* Legal Disclaimer */}
          <div style={{
            background: 'var(--amber-50)', border: '1px solid var(--amber-500)',
            borderRadius: 'var(--radius-md)', padding: '1.25rem 1.5rem',
            marginBottom: '2.5rem', display: 'flex', gap: '1rem', alignItems: 'flex-start',
          }}>
            <AlertTriangle size={22} style={{ color: 'var(--amber-600)', flexShrink: 0, marginTop: '2px' }} />
            <div>
              <div style={{ fontWeight: 700, color: 'var(--amber-800)', marginBottom: '0.25rem' }}>Legal Review Required</div>
              <p style={{ fontSize: '0.875rem', color: 'var(--amber-800)', lineHeight: 1.6 }}>
                These terms and conditions are a template for demonstration purposes. They must be reviewed, customized, and approved by a qualified legal professional before being used in a production environment. Laws and regulations vary by jurisdiction.
              </p>
            </div>
          </div>

          <div className="card" style={{ padding: '2.5rem' }}>
            <p style={{ fontSize: '0.95rem', color: 'var(--text-muted)', lineHeight: 1.7, marginBottom: '2rem' }}>
              Welcome to NourishLink. Please read these Terms and Conditions carefully before using our Smart Food Donation Platform. By using the Platform, you agree to comply with and be bound by the following terms.
            </p>

            {sections.map((section, i) => (
              <div key={i} style={{ marginBottom: '2rem' }}>
                <h2 style={{ fontSize: '1.15rem', fontWeight: 700, color: 'var(--text-main)', marginBottom: '0.75rem' }}>
                  {section.title}
                </h2>
                <div style={{ fontSize: '0.9rem', color: 'var(--text-muted)', lineHeight: 1.8, whiteSpace: 'pre-line' }}>
                  {section.content}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>
    </div>
  );
};

export default TermsPage;
